### PR TITLE
Align the table header to the tabel when labels are used

### LINKED ISSUE #49: Add option to show row labels in static tables
Currently it is hardcoded to override the `Grid(layout)`, but it should be configurable.

Needed for https://github.com/PandABlocks/PandABlocks-ioc/pull/62

### PR DESCRIPTION
**Pull request by evalott100**
Closes #49

### CODE REVIEW

**Comment by evalott100** [comment]
### Report

If no labels are added everything stays the same:

image

If labels are added the header indents correctly:

image

It doesn't matter how many elements are included:

image

image

**Comment by GDYendell** [comment]
Thanks for the screenshots! :pray:

**Comment by evalott100** [comment]
> Thanks for including the screenshots! 🙏

No worries! In those larger table pics they are off by one or two pixels , but I've since fixed that by casting `component_bounds.w` to `int`after scaling

**Comment by evalott100** [comment]
Closing to work off branch on upstream https://github.com/epics-containers/pvi/pull/63

**Pull request closed without merging**
