### PR TITLE
Convert to use pydantic

### LINKED ISSUE #9: Try using discriminator
This might help with performance:
https://wyfo.github.io/apischema/0.17/optimizations_and_benchmark/#discriminator

### LINKED ISSUE #65: Update to use pydantic

### PR DESCRIPTION
**Pull request by GDYendell**
Fixes #65 
Closes #9 as not needed

### CODE REVIEW

**Comment by GDYendell** [comment]
Here it is @gilesknap

**Comment by GDYendell** [comment]
One thing that I don't like about this is that the `type` discriminator field of the models is not considered special and that means serialization cannot use `exclude_default=True`, because the values are the default and only possible value for the field. It can only use `exclude_none=True` This means that any field of a model that shouldn't appear in the converted output cannot use default values, it must use None and manually convert to the default value in a getter or in the caller code.

I did quite a lot of searching and I think this is currently an unsolved problem in pydantic v2. It is quite a lot of extra work for the user to make sure the discriminator so that the code knows what specific type to instantiate. Maybe there will be a better way in future.

**Comment by gilesknap** [comment]
> One thing that I don't like about this is that the `type` discriminator field of the models is not considered special and that means serialization cannot use `exclude_default=True`, because the Literal strings are the default and only possible value for the field. It can only use `exclude_none=True`. This means that any field of a model that shouldn't appear in the converted output cannot use default values, it must use `None` and manually convert to the default value in a getter or in the caller code.
> 
> I did quite a lot of searching and I think this is currently an unsolved problem in pydantic v2. It is quite a lot of extra work for the user to make sure the discriminator is included in the serialized output so that the code knows what specific type to instantiate when deserializing. Maybe there will be a better way in future.

I also see this problem in ibek. It makes the yaml more verbose that necessary but is not an absolute disaster.

**Comment by gilesknap** [comment]
I'm not sure I can do a meaningful review of this code without spending a week or so getting my head into it. I will instead, try out this version against ibek and see if the example usage that I have still works.

Will try to get that done this afternoon 15 Jan.

**Review by gilesknap — APPROVED** [review]
I tried this out in an ioc-adsimdetector example. I noticed that ibek's call to the constructor of IndexEntry needed to have its positional arguments made into keyword.

I then verified that it ran OK and generated the same bob files as the previous version.

So I think it's good to go.

**Pull request merged**
