### PR TITLE
Improvements to convert for pmac

### PR DESCRIPTION
**Pull request by GDYendell**

### CODE REVIEW

**Comment by GDYendell** [comment]
@gilesknap this makes convert run and do ~sensible things for `pmacController`. It doesn't yet keep hold of the macros. I will investigate what the consequences of that might be.

**Comment by gilesknap** [comment]
OK, nice.  pmacController converts fine.

Now I'm having a go at an axis.

Please could we get this error
```
AssertionError: Can't find device class and parent class in header file
```
To print the names of the things it can't find?

**Comment by gilesknap** [comment]
I don't suppose pvi knows about the motor record?

```
pvi convert device /workspaces/ioc-pmac/ibek-support/motor  /epics/support/motor/motorApp/MotorSrc/asynMotorController.h  --template /epics/s
upport/motor/db/basic_asyn_motor.db
Traceback (most recent call last):

  File "/workspaces/pvi/src/pvi/_convert/_asyn_convert.py", line 61, in asyn_component_type
    return record_types[self.type]

KeyError: 'motor'


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

  File "/venv/bin/pvi", line 8, in <module>
    sys.exit(app())

  File "/workspaces/pvi/src/pvi/__main__.py", line 103, in device
    component_group = TemplateConverter(templates).convert()

  File "/workspaces/pvi/src/pvi/_convert/_template_convert.py", line 32, in convert
    self.templates, self._extract_components()

  File "/workspaces/pvi/src/pvi/_convert/_template_convert.py", line 43, in _extract_components
    component = parameter.generate_component()

  File "/workspaces/pvi/src/pvi/_convert/_asyn_convert.py", line 119, in generate_component
    asyn_cls = self.write_record.asyn_component_type()

  File "/workspaces/pvi/src/pvi/_convert/_asyn_convert.py", line 63, in asyn_component_type
    raise KeyError(

KeyError: " asyn type motor({'DESC': '$(DESC)', 'DTYP': '$(DTYP)', 'DIR': '$(DIR)', 'VELO': '$(VELO)', 'VBAS': '$(VBAS)', 'ACCL': '$(ACCL)', 'ACCU': '$(ACCU=0)', 'BDST': '$(BDST)', 'BVEL': '$(BVEL)', 'BACC': '$(BACC)', 'OUT': '@asyn($(PORT),$(ADDR))', 'MRES': '$(MRES)', 'PREC': '$(PREC)', 'EGU': '$(EGU)', 'DHLM': '$(DHLM)', 'DLLM': '$(DLLM)', 'INIT': '$(INIT)', 'TWV': '1'}) not found in['ao', 'bo', 'busy', 'longout', 'mbbo', 'stringout']"

[pmac](convert-name-handling)[pvi]$ 
```

**Comment by gilesknap** [comment]
I still think we should merge this by the way. It is a big improvement to the convert process.

**Comment by GDYendell** [comment]
> To print the names of the things it can't find?

It doesn't currently know the classes. That is why it is searching for a specific pattern. We could just provide the device and parent class on the command line, perhaps optionally, but I think it would still make sense to try to verify that those classes are correct. Maybe the pattern is still too strict? What is the class definition in this case?

**Comment by GDYendell** [comment]
> KeyError: 'motor'

I think this is just because motor records just aren't implemented currently.

**Pull request merged**
